# Generated by Django 5.0.6 on 2025-05-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremas', '0002_carrito_session_key_alter_carrito_id_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
