# Generated by Django 5.2.1 on 2025-06-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremas', '0003_pedido_total_pedido_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
