# Generated by Django 5.2.1 on 2025-06-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremas', '0004_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_despacho',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_entrega',
            field=models.CharField(choices=[('Domicilio', 'Domicilio'), ('Retiro en Tienda', 'Retiro en Tienda')], default='Domicilio', max_length=50),
        ),
    ]
