# Generated by Django 5.2.1 on 2025-06-03 01:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremas', '0005_pedido_estado_despacho_pedido_metodo_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Por Registrar', 'Por Registrar'), ('Registrado', 'Registrado')], default='Por Registrar', max_length=20)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferremas.pedido')),
            ],
        ),
    ]
