# Generated by Django 5.2.1 on 2025-06-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremas', '0007_encuestasatisfaccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='fecha',
            new_name='fecha_entrega',
        ),
    ]
