# Generated by Django 5.2.1 on 2025-06-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremas', '0009_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
