# Generated by Django 5.2.4 on 2025-07-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremas', '0010_promocion_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='uid_auth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
