# Generated by Django 5.2.4 on 2025-07-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremas', '0011_usuario_uid_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='uid_auth',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
